# Site settings
baseurl = "https://catalog.summittdweller.com"
languageCode = "en-us"
sectionPagesMenu = "main"

[params]
	name = "Summitt Catalog"
	description = "Tracking the commmunity kitties. Site creation and upkeep by Mark and Mackenzie McFate."
	email = "mark.mcfate@icloud.com"
	author = "Summitt Catalog"
